server:
  port: 8766
spring:
  application:
    name: eureka-zuul-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    wo:
      path: /wo/**
      serviceId: eureka-client
    ni:
      path: /ni/**
      serviceId: eureka-feign-client